# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

MINIMAX_H3_CANVAS_MULTIPLE = 32
MINIMAX_H3_SUPPORTED_FPS = 24
MINIMAX_H3_MIN_DURATION_SECONDS = 4.0
MINIMAX_H3_MAX_DURATION_SECONDS = 15.0
